In [24]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [25]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp,yt in zip(y_predicted,y_true):
        total_error += abs(yt-yp)
    print(total_error)
    mae = total_error / len(y_true)
    return mae

In [26]:
min = mae(y_predicted,y_true)
min

2.5


0.5

In [27]:
#Absolute Error
np.sum(np.abs(y_predicted - y_true))

2.5

In [28]:
#MeanAbsolute Error
np.mean(np.abs(y_predicted - y_true))

0.5

In [29]:
#Log Loss or Cross Binary Entropy
epsilon = 1e-15
y_predicted

array([1, 1, 0, 0, 1])

In [36]:
# Using numpy.clip to ensure values are within the specified range
y_predicted_new = np.clip(y_predicted, epsilon, 1-epsilon).astype(np.float64)

print(y_predicted_new)

[1.e+00 1.e+00 1.e-15 1.e-15 1.e+00]


In [38]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [40]:
-np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

17.2696280766844

In [41]:
def log_loss(y_predicted , y_true):
    y_predicted_new = np.clip(y_predicted, epsilon, 1-epsilon).astype(np.float64)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))

In [42]:
log_loss(y_predicted , y_true)

17.2696280766844

In [47]:
#Mean Square Error
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)

In [48]:
mse(y_predicted , y_true)

Total Squared Error: 1.83
Mean Squared Error: 0.366


In [ ]:
#Mean Square Error using numpy
np.mean(np.square(y_true-y_predicted))