In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [4]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
#Broadcasting
broadcasting = price_per_unit * units
broadcasting

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [6]:
#dot Product
dot_product = np.dot(price_per_unit, units)
dot_product

array([34400, 50000, 64400])

In [8]:
inr_change = 75
revenue_dollar = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue_inr = revenue_dollar * inr_change
revenue_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])