In [28]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [29]:
df = pd.read_csv('insurance_data.csv');
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [30]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train , y_test = train_test_split(df[['age','affordibility']], 
                                                      df.bought_insurance, test_size = 0.2,random_state = 25)

In [31]:
x_train_s = x_train.copy()
x_train_s['age'] = x_train_s['age'] / 100

x_test_s = x_test.copy()
x_test_s['age'] = x_test_s['age'] / 100
x_train_s.head()

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1

In [32]:
model = keras.Sequential([
    keras.layers.Dense(1,input_shape = (2,),activation = 'sigmoid',kernel_initializer = 'ones',bias_initializer = 'zeros')])

model.compile(optimizer = 'adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

C:\Users\NoteBook\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.fit(x_train_s, y_train, epochs = 5000)

Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 401ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy

In [35]:
model.evaluate(x_test_s, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.3550


[0.3549776077270508, 1.0]

In [36]:
model.predict(x_test_s)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[0.70548487],
       [0.3556957 ],
       [0.16827832],
       [0.47801185],
       [0.72606957],
       [0.8294983 ]], dtype=float32)

In [37]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [38]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))

In [16]:
#Building Nueral Network from Scratch

In [39]:
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [40]:
def prediction_function(age,affordibility):
    weighted_sum = coef[0] * age + coef[1] * affordibility + intercept
    return sigmoid(weighted_sum)

In [41]:
prediction_function(0.47, 1)

C:\Users\NoteBook\AppData\Local\Temp\ipykernel_64236\3686314171.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.705484819775958

In [42]:
epsilon = 1e-15
def log_loss(y_predicted , y_true):
    y_predicted_new = np.clip(y_predicted, epsilon, 1-epsilon).astype(np.float64)
    return -np.mean(y_true * np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))


In [43]:
def sigmoid_numpy(X):
    return 1 / (1 + np.exp(-X))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [49]:
def gradient_descent(age,affordibility, y_true, epochs, loss_threshold):
    # w1, w2, bias
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordibility + bias
        y_predicted = sigmoid_numpy(weighted_sum)

        loss = log_loss(y_predicted, y_true)

        w1d = (1/n) * np.dot(np.transpose(age) , (y_predicted - y_true))
        w2d = (1/n) * np.dot(np.transpose(affordibility) , (y_predicted - y_true))
        
        bias_d = np.mean(y_predicted - y_true)

        w1 = w1 - rate *w1d
        w2 = w2 - rate *w2d

        bias = bias - rate * bias_d

        print(f'Epoch:{i}, w_age:{w1}, w_affordability:{w2}, bias:{bias}, loss:{loss}')
        if loss <= loss_threshold:
            break
    return w1,w2, bias


In [51]:
gradient_descent(x_train_s['age'],x_train_s['affordibility'], y_train, 1000,0.4631)

Epoch:0, w_age:0.974907633470177, w_affordability:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:1, w_age:0.9556229728273669, w_affordability:0.9058873696677865, bias:-0.2122349122718517, loss:0.681264778737757
Epoch:2, w_age:0.9416488476693794, w_affordability:0.8719790823960313, bias:-0.2977578997796538, loss:0.6591474252715025
Epoch:3, w_age:0.9323916996249162, w_affordability:0.8457541517722915, bias:-0.3715094724003511, loss:0.6431523291301917
Epoch:4, w_age:0.9272267472726993, w_affordability:0.8262362885332687, bias:-0.43506643026891584, loss:0.6316873063379158
Epoch:5, w_age:0.9255469396815343, w_affordability:0.8124402814952774, bias:-0.48994490058938817, loss:0.623471707997592
Epoch:6, w_age:0.9267936114129968, w_affordability:0.8034375029757677, bias:-0.5375299543522853, loss:0.6175321183044205
Epoch:7, w_age:0.93047170420295, w_affordability:0.7983920007454487, bias:-0.5790424270894963, loss:0.6131591858705934
Epoch:8, w_age:0.9361540784567942, 

(5.051047623653049, 1.4569794548473887, -2.9596534546250037)

In [52]:
coef , intercept 

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))